"""Regenerate ``index.json`` and ``modalities.md`` from the current notes/.

The consolidated ``insights.md`` guidebook is regenerated separately by an
LLM agent in the orchestrating session — it requires synthesis across many
notes, which is out of scope for a deterministic script. This script does
guarantee an ``insights.md`` placeholder exists with a "regenerate me" note
if absent.

Usage::

    uv run -- python -m survey_bio_fm.scripts.consolidate
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import Counter, defaultdict

from survey_bio_fm.notes import REPO_ROOT, load_all_notes

logger = logging.getLogger(__name__)


def write_index() -> int:
    notes = load_all_notes()
    entries = [n.to_frontmatter() for n in notes]
    out = REPO_ROOT / "index.json"
    out.write_text(
        json.dumps({"count": len(entries), "papers": entries}, indent=2),
        encoding="utf-8",
    )
    logger.info("wrote %s (%d papers)", out, len(entries))
    return len(entries)


def write_modalities_md() -> None:
    notes = load_all_notes()
    by_mod: dict[str, list] = defaultdict(list)
    for n in notes:
        for m in n.modalities:
            by_mod[m].append(n)
    status_counts = Counter(n.status for n in notes)
    lines: list[str] = ["# Bio-FM Survey — Per-Modality Index\n"]
    lines.append(f"Total papers: **{len(notes)}**\n")
    lines.append("Status breakdown:")
    for s, c in sorted(status_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- `{s}`: {c}")
    lines.append("")
    for mod in sorted(by_mod):
        ns = sorted(by_mod[mod], key=lambda n: (-(n.year or 0), n.title.lower()))
        lines.append(f"## {mod} ({len(ns)} papers)\n")
        lines.append("| Year | Title | Status | Params | Tokens | Tags |")
        lines.append("|------|-------|--------|--------|--------|------|")
        for n in ns:
            tags = ", ".join(n.tags[:4])
            title_link = f"[{n.title}](notes/{n.id}.md)"
            lines.append(
                f"| {n.year or '—'} | {title_link} | `{n.status}` "
                f"| {n.parameters or '—'} | {n.training_tokens or '—'} | {tags} |"
            )
        lines.append("")
    out = REPO_ROOT / "modalities.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    logger.info("wrote %s", out)


def ensure_insights_placeholder() -> None:
    out = REPO_ROOT / "insights.md"
    if out.exists():
        return
    out.write_text(
        "# Bio-FM Training Guidebook\n\n"
        "_This guidebook is regenerated by an LLM synthesis agent. Run the "
        "orchestrating session to populate it._\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("-v", "--verbose", action="store_true")
    args = p.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )
    n = write_index()
    write_modalities_md()
    ensure_insights_placeholder()
    print(f"Consolidated {n} papers.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
